image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm install --msvs_version=2015

build_script:
  - yarn dist

build: OFF
test: OFF
deploy: OFF
